### ISSUE TITLE
NamedArgumentForDataProviderRector only changing the first data provider

### ISSUE THREAD

**Issue by gnutix** [rectorphp/rector-phpunit#345] opened 2024-06-29 12:31 UTC
Hey there,

I've ran NamedArgumentForDataProviderRector on my project and noticed it only refactors the first `#[DataProvider]` it encounters. On my project, it missed about a 1/3 of the deprecations.

Changing `getDataProviderMethodName` to return an array of method names : 

```php
    private function getDataProviderMethodNames(ClassMethod $classMethod) : array
    {
        $methodNames = [];
        $attributeClassName = DataProvider::class;
        foreach ($classMethod->attrGroups as $attributeGroup) {
            foreach ($attributeGroup->attrs as $attribute) {
                if (!$this->isName($attribute->name, $attributeClassName)) {
                    continue;
                }
                foreach ($attribute->args as $arg) {
                    if ($arg->value instanceof String_) {
                        $methodNames[] = $arg->value->value;
                    }
                }
            }
        }
        return $methodNames;
    }
```

and calling it like this : 

```php
            $dataProviderMethodNames = $this->getDataProviderMethodNames($classMethod);
            if ($dataProviderMethodNames === []) {
                continue;
            }
            foreach ($dataProviderMethodNames as $dataProviderMethodName) {
                // ... rest of the code untouched
            }
```

fixes the issue. /cc @marcelthole

gnutix

**Comment by TomasVotruba** [comment] 2024-06-29 22:25
Great :+1:  Could you send the PR with fix? :)

**Comment by gnutix** [comment] 2024-06-29 23:17
Sorry, too much on my plate these days.

**Comment by TomasVotruba** [comment] 2024-06-30 08:38
No worries :+1: 

Closing as duplicate of similar issue to keep focus: https://github.com/rectorphp/rector-phpunit/issues/346#issuecomment-2198370779

**Comment by gnutix** [comment] 2024-06-30 09:32
Without this fix, the rule is only partially doing its job, and the "optional feature" triggers deprecations that are outputted by PHUnit. So please, don't close this issue, it's a separate problem from the other you've linked.

**Comment by TomasVotruba** [comment] 2024-06-30 09:59
I missunderstood then. We'll need a failing demo link first.

**Comment by marcelthole** [comment] 2024-07-01 06:07
I added a failing testcase and fixed that case. We didn't had the case with multiple dataproviders on a single test method. But it should be fixed now :)

**Closed** 2024-07-01 06:12 UTC
